from building import *

cwd = GetCurrentDir()

# Application sources
src = Glob('*.c') + Glob('*.cpp')

# Verilated DUT and runtime support
verilated_dut_dir = os.path.join(cwd, 'verilated_dut_150')
verilator_rt_dir = os.path.join(cwd, 'verilator_runtime')

# Only pull in the bits of the Verilated runtime we need for a single-threaded,
# non-tracing simulation on RT-Thread.
verilator_runtime_src = [
    os.path.join('verilator_runtime', name)
    for name in [
        'verilated.cpp',
        'verilated_random.cpp',
        'verilated_threads.cpp',
    ]
]

src += Glob(os.path.join('verilated_dut_150', '*.cpp'))
src += [File(path) for path in verilator_runtime_src]

CPPPATH = [cwd, verilated_dut_dir, verilator_rt_dir]
CPPDEFINES = ['VL_RT_THREAD']

group = DefineGroup(
    'Applications', src, depend=[''], CPPPATH=CPPPATH, CPPDEFINES=CPPDEFINES
)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
